// Generated by LiveScript 1.2.0
(function(){
  chrome.runtime.onMessage.addListener(function(request, sender, sendResponse){
    console.log('message');
    if (request != null && request.feedlearn === 'getformat') {
      console.log('right type');
      return chrome.cookies.get({
        url: 'http://feedlearn.herokuapp.com/',
        name: 'format'
      }, function(cookie){
        console.log('got cookies');
        console.log(cookie.value);
        sendResponse({
          feedlearn: true,
          format: cookie.value
        });
        chrome.tabs.query({}, function(tabs){
          var i$, len$, tab, results$ = [];
          for (i$ = 0, len$ = tabs.length; i$ < len$; ++i$) {
            tab = tabs[i$];
            results$.push(chrome.tabs.sendMessage(tab.id, {
              feedlearn: true,
              format: cookie.value
            }));
          }
          return results$;
        });
        return true;
      });
    }
  });
}).call(this);
