// Generated by LiveScript 1.2.0
(function(){
  var root, insertBeforeItem, insertIfMissing, initialize, preinitialize, loadfirststart;
  root = typeof exports != 'undefined' && exports !== null ? exports : this;
  insertBeforeItem = function(jfeeditem){
    return jfeeditem.before($('<iframe>').css({
      width: '495px',
      height: '300px'
    }).attr('src', 'https://feedlearn.herokuapp.com?facebook=true').attr('frameBorder', '0'));
  };
  root.numitems = 0;
  insertIfMissing = function(){
    var i$, ref$, len$, feeditem, jfeeditem, results$ = [];
    for (i$ = 0, len$ = (ref$ = $('.mbm')).length; i$ < len$; ++i$) {
      feeditem = ref$[i$];
      jfeeditem = $(feeditem);
      if (!jfeeditem.attr('feedlearninserted')) {
        jfeeditem.attr('feedlearninserted', true);
        root.numitems += 1;
        if (root.numitems % 10 === 5) {
          results$.push(insertBeforeItem(jfeeditem));
        }
      }
    }
    return results$;
  };
  root.mostrecentmousemove = Date.now();
  root.timeopened = Date.now();
  initialize = function(format){
    var fburl, fbname;
    if (!(format === 'link' || format === 'interactive' || format === 'none')) {
      fburl = $('.fbxWelcomeBoxName').attr('href');
      fbname = $('.fbxWelcomeBoxName').text();
      chrome.runtime.sendMessage({
        feedlearn: 'missingformat',
        fburl: fburl,
        fbname: fbname
      });
    }
    if (format !== 'none') {
      setInterval(function(){
        return insertIfMissing();
      }, 1000);
    }
    $(document).mousemove(function(){
      return root.mostrecentmousemove = Date.now();
    });
    return setInterval(function(){
      var fburl, fbname;
      fburl = $('.fbxWelcomeBoxName').attr('href');
      fbname = $('.fbxWelcomeBoxName').text();
      return chrome.runtime.sendMessage({
        feedlearn: 'fbstillopen',
        mostrecentmousemove: root.mostrecentmousemove,
        timeopened: root.timeopened,
        timesincemousemove: Date.now() - root.mostrecentmousemove,
        fburl: fburl,
        fbname: fbname
      });
    }, 5000);
  };
  preinitialize = function(format){
    if ($('#feedlearn').length === 0) {
      clearInterval(root.firststartprocess);
      $('html').append($('<div>').attr('id', 'feedlearn').css({
        position: 'absolute',
        display: 'none',
        top: '0px',
        left: '0px',
        zIndex: 1000
      }));
      return initialize(format);
    }
  };
  chrome.runtime.onMessage.addListener(function(request, sender){
    if (request.feedlearn) {
      return preinitialize(request.format);
    }
  });
  loadfirststart = function(){
    var fburl, fbname;
    if ($('#feedlearn').length === 0) {
      fburl = $('.fbxWelcomeBoxName').attr('href');
      fbname = $('.fbxWelcomeBoxName').text();
      console.log('fburl:' + fburl);
      console.log('fbname:' + fbname);
      return chrome.runtime.sendMessage({
        feedlearn: 'getformat',
        fburl: fburl,
        fbname: fbname
      });
    }
  };
  loadfirststart();
  root.firststartprocess = setInterval(loadfirststart, 5000);
}).call(this);
