// Generated by LiveScript 1.3.1
(function(){
  $('#extensioninstalledcheck').css('visibility', 'visible');
  $('#extensioninstalleddisplay').css('color', 'green').text('FeedLearn Chrome Extension has been installed!');
  $('#extensioninstallbutton').attr('disabled', true);
}).call(this);
