// Generated by LiveScript 1.2.0
(function(){
  var root, insertBeforeItem, insertIfMissing, initialize, preinitialize;
  root = typeof exports != 'undefined' && exports !== null ? exports : this;
  insertBeforeItem = function(jfeeditem){
    return jfeeditem.before($('<iframe>').css({
      width: '495px',
      height: '300px'
    }).attr('src', 'https://feedlearn.herokuapp.com?facebook=true').attr('frameBorder', '0'));
  };
  root.numitems = 0;
  insertIfMissing = function(){
    var i$, ref$, len$, feeditem, jfeeditem, results$ = [];
    for (i$ = 0, len$ = (ref$ = $('.mbm')).length; i$ < len$; ++i$) {
      feeditem = ref$[i$];
      jfeeditem = $(feeditem);
      if (!jfeeditem.attr('feedlearninserted')) {
        jfeeditem.attr('feedlearninserted', true);
        root.numitems += 1;
        if (root.numitems % 10 === 5) {
          results$.push(insertBeforeItem(jfeeditem));
        }
      }
    }
    return results$;
  };
  initialize = function(){
    return setInterval(function(){
      return insertIfMissing();
    }, 1000);
  };
  preinitialize = function(){
    if (window.location.toString() === 'https://www.facebook.com/' && $('#feedlearn').length === 0) {
      console.log('feedlearn loaded');
      $('html').append($('<div>').attr('id', 'feedlearn').css({
        position: 'absolute',
        display: 'none',
        top: '0px',
        left: '0px',
        zIndex: 1000
      }));
      return initialize();
    }
  };
  chrome.runtime.onMessage.addListener(function(request, sender){
    if (request.feedlearn && request.format !== 'none') {
      return preinitialize();
    }
  });
  chrome.runtime.sendMessage({
    feedlearn: 'getformat'
  });
}).call(this);
